image: node:14

cache:
  paths:
    - node_modules/

stages:
  - install
  - image

install_packages:
  stage: install
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

build_image:
  stage: image
  image: docker:stable
  services:
    - name: docker:dind
      alias: dockerdaemon
  variables:
    DOCKER_HOST: tcp://dockerdaemon:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Building docker image"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker build . -t gge2705/netflix-clone-frontend
    - docker push gge2705/netflix-clone-frontend