import P0 from "../images/profiles/profiles_pic/p0.png";
import P1 from "../images/profiles/profiles_pic/p1.png";
import P2 from "../images/profiles/profiles_pic/p2.png";
import P3 from "../images/profiles/profiles_pic/p3.png";
import P4 from "../images/profiles/profiles_pic/p4.png";
import P5 from "../images/profiles/profiles_pic/p5.png";
import P6 from "../images/profiles/profiles_pic/p6.png";
import P7 from "../images/profiles/profiles_pic/p7.png";
import P8 from "../images/profiles/profiles_pic/p8.png";
import P9 from "../images/profiles/profiles_pic/p9.png";
import P10 from "../images/profiles/profiles_pic/p10.png";
import P11 from "../images/profiles/profiles_pic/p11.png";
import P12 from "../images/profiles/profiles_pic/p12.png";
import P13 from "../images/profiles/profiles_pic/p13.png";
import P14 from "../images/profiles/profiles_pic/p14.png";
import P15 from "../images/profiles/profiles_pic/p15.png";
import P16 from "../images/profiles/profiles_pic/p16.png";
import P17 from "../images/profiles/profiles_pic/p17.png";
import P18 from "../images/profiles/profiles_pic/p18.png";
import P19 from "../images/profiles/profiles_pic/p19.png";
import P20 from "../images/profiles/profiles_pic/p20.png";
import P21 from "../images/profiles/profiles_pic/p21.png";

export const profile_pic = [P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16, P17, P18, P19, P20, P21];
