type MoviesActionTypesT = {
    DISCOVER_MOVIES: string,
    GET_MOVIE: string,
    GET_MOVIE_CREDIT: string,
    RESET_MOVIE_STORE: string,
    MORE_LIKE_THIS_MOVIE: string,
    UPCOMING_MOVIES: string,
    TOP_RATED_MOVIES: string,
    TRENDING_MOVIES: string
}

export const MoviesActionTypes: MoviesActionTypesT = {
    DISCOVER_MOVIES: 'DISCOVER_MOVIES',
    GET_MOVIE: 'GET_MOVIE',
    GET_MOVIE_CREDIT: 'GET_MOVIE_CREDIT',
    MORE_LIKE_THIS_MOVIE: 'MORE_LIKE_THIS_MOVIE',
    RESET_MOVIE_STORE: 'RESET_MOVIE_STORE',
    UPCOMING_MOVIES: 'UPCOMING_MOVIES',
    TOP_RATED_MOVIES: 'TOP_RATED_MOVIES',
    TRENDING_MOVIES: 'TRENDING_MOVIES'
}