type UTILS_ACTION_TYPES = {
    APPLICATION_LANGUAGE: string
    MOVIE_GENRES: string
    SERIES_GENRES: string
}

export const UtilsActionTypes: UTILS_ACTION_TYPES = {
    APPLICATION_LANGUAGE: 'APPLICATION_LANGUAGE',
    MOVIE_GENRES: 'MOVIE_GENRES',
    SERIES_GENRES: 'SERIES_GENRES'
}