type UTILS_ACTION_TYPES = {
    APPLICATION_LANGUAGE: string
    MOVIE_GENRES: string
    SERIES_GENRES: string,
    MEDIA_TYPE: string,
    RESET_MEDIA_TYPE: string
    SHOW_MODAL: string,
    SEARCH_RESULT: string
    SEARCH_QUERY: string
    RESET_SHOW_MODAL: string
    RESET_SEARCH_RESULT: string
}

export const UtilsActionTypes: UTILS_ACTION_TYPES = {
    APPLICATION_LANGUAGE: 'APPLICATION_LANGUAGE',
    MOVIE_GENRES: 'MOVIE_GENRES',
    SERIES_GENRES: 'SERIES_GENRES',
    MEDIA_TYPE: 'MEDIA_TYPE',
    RESET_MEDIA_TYPE: 'RESET_MEDIA_TYPE',
    SHOW_MODAL: 'SHOW_MODAL',
    SEARCH_RESULT: 'SEARCH_RESULT',
    SEARCH_QUERY: 'SEARCH_QUERY',
    RESET_SHOW_MODAL: 'RESET_SHOW_MODAL',
    RESET_SEARCH_RESULT: 'RESET_SEARCH_RESULT'
}